before_cache:
  # The stats cache contains timestamped reports unused by CI but that
  # thrash the cache.  Skip caching these.
  - rm -rf ${HOME}/.cache/pants/stats

cache:
  directories:
    - ${HOME}/.cache/pants

language: python
python:
  - '3.4'
  - '3.5'
  - '3.6'

script:
  - ./build-support/travis/build.sh

after_success:
  - coveralls
