before_cache:
  # Ensure permissions to do the below removals, which happen with or without caching enabled.
  #- sudo chown -R travis:travis "${HOME}" "${TRAVIS_BUILD_DIR}"
  # The stats cache contains timestamped reports unused by CI but that
  # thrash the cache.  Skip caching these.
  - rm -rf ${HOME}/.cache/pants/stats

cache:
  directories:
    - ${HOME}/.cache/pants

language: python
python:
  - '2.7'

script:
  - ./build-support/travis/build.sh

after_success:
  - coveralls
