[GLOBAL]
pants_version = "2.7.0"

backend_packages = [
  'pants.backend.python',
  'pants.backend.python.lint.black',
  'pants.backend.python.lint.isort',
  'pants.backend.python.lint.flake8',
  'pants.backend.python.typecheck.mypy',
  'pants.backend.experimental.docker',
]

[source]
root_patterns = [
  '/3rdparty/python',
  '/src/python',
  '/src/docker',
  '/tests/python',
]

[python-setup]
# The default interpreter compatibility for code in this repo. Individual targets can override
#  this with the `interpreter_constraints` field. See
#  https://www.pantsbuild.org/docs/python-interpreter-compatibility.
interpreter_constraints = [">=3.8"]

# Use a constraints file. See https://www.pantsbuild.org/docs/python-third-party-dependencies.
requirement_constraints = "3rdparty/python/constraints.txt"

# We search for interpreters on both on the $PATH and in the `$(pyenv root)/versions` folder.
#  If you're using macOS, you may want to leave off the <PATH> entry to avoid using the
#  problematic system Pythons. See
#  https://www.pantsbuild.org/docs/python-interpreter-compatibility#changing-the-interpreter-search-path.
interpreter_search_paths = ["<PATH>", "<PYENV>"]

[flake8]
config = ".flake8"

[isort]
config = [".isort.cfg"]

[mypy]
config = ".mypy.ini"

# Let's be a good OSS citizen!
[anonymous-telemetry]
enabled = true
repo_id = "a20f5ec5-297a-4ed3-9cc2-ea96a5224015"
