# Define a library containing everything within this folder/package
# (by default) that other targets can depend on.

python_library(
  dependencies=[
    '3rdparty/python:numpy',
  ],
  compatibility=['CPython>=2.7,<3', 'CPython>=3.4']
)
